site_name: Требования КриптоАРМ
site_url: https://OlgaGaz.github.io/mkdocs-test/
theme:
  name: material
  palette:
    primary: black
    features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
site_author: Olga Gazizova
extra:
  version:
    provider: mike
